version: '3'
services:
  pig-mysql:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pig-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
     - /opt/mysql_data:/var/lib/mysql
     - /mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - pig-net

  pig-redis:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-redis
    container_name: pig-redis
    ports:
      - 6379:6379
    networks:
      - pig-net

  pig-rabbitmq:
     image: rabbitmq:alpine
     container_name: pig-rabbitmq
     restart: always
     volumes:
       - ./data/rabbitmq:/var/lib/rabbitmq
     networks:
       - pig-net
     ports:
       - 5672:5672
 
  pig-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    container_name: ics-eureka
    restart: always
    ports:
      - 1025:1025
    hostname: discovery
    networks:
      - pig-net




  pig-auth:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    container_name: pig-auth
    restart: always
    ports:
      - 9060:9060
    environment:
          - RABBIT_MQ_HOST=rabbitmq
          - RABBIT_MQ_PORT=5672
          - RABBIT_MQ_USERNAME=guest
          - RABBIT_MQ_PASSWORD=guest
          - EUREKA_ZONE_HOST=discovery
          - EUREKA_ZONE_PORT=1025
          - REDIS_HOST=redis
          - REDIS_PORT=6379
          - REDIS_PASSWORD=123456
          - MYSQL_HOST=mysql
          - MYSQL_PORT=3306
          - MYSQL_USERNAME=root
          - MYSQL_PASSWORD=admin
    depends_on:
          - pig-eureka
          - pig-mysql
          - pig-redis
          - pig-rabbitmq
    networks:
      - pig-net

  pig-upms:
    build:
      context: ./
      dockerfile: Dockerfile-upms
    container_name: pig-upms
    restart: always
    ports:
      - 8001:8001
    environment:
           - RABBIT_MQ_HOST=rabbitmq
           - RABBIT_MQ_PORT=5672
           - RABBIT_MQ_USERNAME=guest
           - RABBIT_MQ_PASSWORD=guest
           - EUREKA_ZONE_HOST=discovery
           - EUREKA_ZONE_PORT=1025
           - REDIS_HOST=redis
           - REDIS_PORT=6379
           - REDIS_PASSWORD=123456
           - MYSQL_HOST=mysql
           - MYSQL_PORT=3306
           - MYSQL_USERNAME=root
           - MYSQL_PASSWORD=admin
    depends_on:
           - pig-eureka
           - pig-mysql
           - pig-redis
           - pig-rabbitmq

    networks:
      - pig-net

  pig-gateway:
    container_name: pig_gateway
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    ports:
      - 9030:9030
    environment:
        - RABBIT_MQ_HOST=rabbitmq
        - RABBIT_MQ_PORT=5672
        - RABBIT_MQ_USERNAME=guest
        - RABBIT_MQ_PASSWORD=guest
        - EUREKA_ZONE_HOST=discovery
        - EUREKA_ZONE_PORT=1025
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_PASSWORD=123456
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=admin
    depends_on:
        - pig-eureka
        - pig-mysql
        - pig-redis
    networks:
        - pig-net

networks:
  pig-net:
    driver: bridge
